"""
AYARLAR DOSYASI
===============
Oyunun tüm sabit ayarları burada.
Renkler, boyutlar, hızlar gibi her şey.
"""

# RENKLER (RGB formatında)
BEYAZ = (255, 255, 255)
SIYAH = (0, 0, 0)
KIRMIZI = (255, 0, 0)
MAVI = (0, 0, 255)
SARI = (255, 255, 0)
ACIK_GRİ = (200, 200, 200)
GRİ = (128, 128, 128)

# EKRAN BOYUTLARI
EKRAN_GENISLIGI = 1200
EKRAN_YUKSEKLIGI = 800
CIZIM_ALANI_YUKSEKLIGI = 600
KONTROL_PANEL_YUKSEKLIGI = 200

# BUTON BOYUTLARI
BUTON_GENISLIGI = 100
BUTON_YUKSEKLIGI = 40
RENK_BUTON_BOYUTU = 40

# HIZ AYARLARI
MIN_HIZ = 2
MAX_HIZ = 8
HIZ_ARTISI = 1

# GÜVENLİK AYARI
# Toplar ekranın kenarlarına çok yakın başlamasın diye
TOP_GUVENLIK_MESAFESI = 20

# ESKİ İNGİLİZCE İSİMLER (geriye uyumluluk için)
WHITE = BEYAZ
BLACK = SIYAH
RED = KIRMIZI
BLUE = MAVI
YELLOW = SARI
LIGHT_GRAY = ACIK_GRİ
GRAY = GRİ
SCREEN_WIDTH = EKRAN_GENISLIGI
SCREEN_HEIGHT = EKRAN_YUKSEKLIGI
DRAWING_AREA_HEIGHT = CIZIM_ALANI_YUKSEKLIGI
CONTROL_PANEL_HEIGHT = KONTROL_PANEL_YUKSEKLIGI
BUTTON_WIDTH = BUTON_GENISLIGI
BUTTON_HEIGHT = BUTON_YUKSEKLIGI
COLOR_BUTTON_SIZE = RENK_BUTON_BOYUTU
MIN_SPEED = MIN_HIZ
MAX_SPEED = MAX_HIZ
SPEED_INCREMENT = HIZ_ARTISI
BALL_MARGIN = TOP_GUVENLIK_MESAFESI
